/* tslint:disable */
/* eslint-disable */
/**
 * Front Test API
 * Тестовое задание для Frontend разработчика
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Fetch200ResponseAllOfData } from './fetch200-response-all-of-data';
// May contain unused imports in some cases
// @ts-ignore
import type { SuccessfulResponse } from './successful-response';

/**
 * @type Fetch200Response
 * @export
 */
export type Fetch200Response = SuccessfulResponse;


