/* tslint:disable */
/* eslint-disable */
/**
 * Front Test API
 * Тестовое задание для Frontend разработчика
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MatchStatus } from './match-status';
// May contain unused imports in some cases
// @ts-ignore
import type { Team } from './team';

/**
 * 
 * @export
 * @interface Match
 */
export interface Match {
    /**
     * Время проведения матча
     * @type {string}
     * @memberof Match
     */
    'time': string;
    /**
     * Название матча
     * @type {string}
     * @memberof Match
     */
    'title': string;
    /**
     * 
     * @type {Team}
     * @memberof Match
     */
    'homeTeam': Team;
    /**
     * 
     * @type {Team}
     * @memberof Match
     */
    'awayTeam': Team;
    /**
     * Счет домашней команды
     * @type {number}
     * @memberof Match
     */
    'homeScore': number;
    /**
     * Счет гостевой команды
     * @type {number}
     * @memberof Match
     */
    'awayScore': number;
    /**
     * 
     * @type {MatchStatus}
     * @memberof Match
     */
    'status': MatchStatus;
}



