/* tslint:disable */
/* eslint-disable */
/**
 * Front Test API
 * Тестовое задание для Frontend разработчика
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Статус матча
 * @export
 * @enum {string}
 */

export const MatchStatus = {
    Scheduled: 'Scheduled',
    Ongoing: 'Ongoing',
    Finished: 'Finished'
} as const;

export type MatchStatus = typeof MatchStatus[keyof typeof MatchStatus];



