/* tslint:disable */
/* eslint-disable */
/**
 * Front Test API
 * Тестовое задание для Frontend разработчика
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Player
 */
export interface Player {
    /**
     * Имя игрока
     * @type {string}
     * @memberof Player
     */
    'username': string;
    /**
     * Количество убийств
     * @type {number}
     * @memberof Player
     */
    'kills': number;
}

