/* tslint:disable */
/* eslint-disable */
/**
 * Front Test API
 * Тестовое задание для Frontend разработчика
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SuccessfulResponse
 */
export interface SuccessfulResponse {
    /**
     * Indicated whether the response is successful.
     * @type {boolean}
     * @memberof SuccessfulResponse
     */
    'ok': boolean;
    /**
     * If successful, response from api
     * @type {object}
     * @memberof SuccessfulResponse
     */
    'data': object;
}

