/* tslint:disable */
/* eslint-disable */
import { Fetch200ResponseAllOfData } from 'api/swagger/model/fetch200-response-all-of-data.ts'

/**
 * Front Test API
 * Тестовое задание для Frontend разработчика
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SuccessfulResponse
 */
export interface SuccessfulResponse {
  /**
   * Indicated whether the response is successful.
   * @type {boolean}
   * @memberof SuccessfulResponse
   */
  ok: boolean
  /**
   * If successful, response from api
   * @type {object}
   * @memberof SuccessfulResponse
   */
  // Почему-то здесь тип был object, а не фактически выводимые данные, а интерфейс Fetch200ResponseAllOfData не используется нигде
  data: Fetch200ResponseAllOfData
}
