/* tslint:disable */
/* eslint-disable */
/**
 * Front Test API
 * Тестовое задание для Frontend разработчика
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Player } from './player';

/**
 * 
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * Название команды
     * @type {string}
     * @memberof Team
     */
    'name': string;
    /**
     * 
     * @type {Array<Player>}
     * @memberof Team
     */
    'players': Array<Player>;
    /**
     * Количество очков
     * @type {number}
     * @memberof Team
     */
    'points': number;
    /**
     * Место в турнирной таблице
     * @type {number}
     * @memberof Team
     */
    'place': number;
    /**
     * Количество убийств
     * @type {number}
     * @memberof Team
     */
    'total_kills': number;
}

